# ─────────────────────────────────────────────────────────────────────────────
# 04-redis-policy.yaml
#
# Redis rules:
#   Ingress – accept connections from backend only (port 6379)
#   Egress  – DNS only
# ─────────────────────────────────────────────────────────────────────────────
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis-policy
  namespace: aura-vault
  labels:
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/part-of: aura-vault
spec:
  podSelector:
    matchLabels:
      app: redis

  policyTypes:
    - Ingress
    - Egress

  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: backend
      ports:
        - protocol: TCP
          port: 6379

  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
